name: Deploy Backend to EC2

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: backend
        run: npm ci
      
      - name: Build TypeScript
        working-directory: backend
        run: npm run build
      
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/dist/*,backend/package*.json,backend/prisma/*"
          target: "/home/ec2-user/hmp/"
          strip_components: 0
      
      - name: Deploy and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/hmp/backend
            npm ci --production
            npx prisma generate
            npx prisma migrate deploy
            pm2 restart hmp-api || pm2 start dist/server.js --name hmp-api
            pm2 save

